//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/LDtk to Unity/6.11.0/Sample/Samples/Typical_2D_platformer_example.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioGame.Level.Enums
{
    /// <summary>
    /// LDtk Enum for LevelEnums
    /// </summary>
    public enum ItemType
    {
        Weapon,
        Healing_Potion
    }

    /// <summary>
    /// LDtk Enum for LevelEnums
    /// </summary>
    public enum WeaponType
    {
        Rifle,
        Shotgun,
        Missile
    }
}